CA='https://cp-algorithms.com/'; UG='https://usaco.guide/'; CFB='https://codeforces.com/blog/entry/'
def T(name,url=None): return {'t':name,'u':url}
def F(title,tags,lo,hi):
    from urllib.parse import quote
    return {'t':f'{title} {lo}–{hi}','u':'https://codeforces.com/problemset?order=BY_SOLVED_DESC&tags='+quote(','.join(tags+[f'{lo}-{hi}']))}
STAGES=[
 {'name':'Return','band':'1350 → 1400','rank':'Pupil → Specialist','lo':0,'hi':1400,'months':'Oct 2026 (built above)',
  'goal':'Get speed back. Fill the four biggest holes: binary search, graphs, DP, range queries.',
  'topics':[T('Everything in the October plan'),T('USACO Guide: Bronze, skim for gaps',UG+'bronze')],'cses':[0,1,2,3],'practice':[F('Any tag',[],900,1300)],
  'contests':['Every Div 2, Div 3, Edu and ABC. Live if work is quiet, else virtual next morning.'],
  'exit':['Rated 1400+ after at least 3 rated rounds','Div 2 A and B in under 30 minutes, 4 rounds in a row','CSES Introductory + first 12 of Sorting & Searching, DP and Graphs done']},
 {'name':'Specialist to Expert','band':'1400 → 1600','rank':'Specialist → Expert','lo':1400,'hi':1600,'months':'4–8 months',
  'goal':'Own the standard toolkit. Stop losing rounds on C. Cut the WA rate in half.',
  'topics':[T('USACO Guide: Silver, all modules',UG+'silver'),T('Binary search on the answer',CA+'num_methods/binary_search.html'),T('Prefix sums, difference arrays',UG+'silver/prefix-sums'),
   T('Two pointers, sliding window',UG+'silver/two-pointers'),T('Sorting + greedy with an exchange argument',UG+'silver/greedy-sorting'),
   T('Monotonic stack and queue',CA+'data_structures/stack_queue_modification.html'),T('Bit tricks, submask enumeration',CA+'algebra/all-submasks.html'),
   T('Sieve, gcd, modular arithmetic',CA+'algebra/sieve-of-eratosthenes.html'),T('Binary exponentiation, modular inverse',CA+'algebra/binary-exp.html'),
   T('Binomial coefficients',CA+'combinatorics/binomial-coefficients.html'),T('BFS, DFS, 0-1 BFS',CA+'graph/01_bfs.html'),
   T('Dijkstra, topological sort, DSU',CA+'graph/dijkstra.html'),T('Trees: subtree sizes, depths, simple tree DP',UG+'gold/dp-trees'),
   T('DP: 1D, 2D, knapsack, LIS',CA+'dynamic_programming/longest_increasing_subsequence.html'),T('Fenwick tree',CA+'data_structures/fenwick.html'),
   T('Segment tree (point update, range query)',CA+'data_structures/segment_tree.html'),T('Sparse table',CA+'data_structures/sparse-table.html'),
   T('String hashing',CA+'string/string-hashing.html'),T('Constructive problems: small cases by hand first')],
  'cses':[0,1,2,3,4,10,12],
  'practice':[F('Mixed',[],1400,1700),F('Binary search',['binary search'],1400,1700),F('Graphs',['graphs'],1400,1700),F('DP',['dp'],1400,1700),F('Data structures',['data structures'],1500,1800),F('Constructive',['constructive algorithms'],1400,1700),F('Number theory',['number theory'],1400,1700)],
  'contests':['Every Div 2, Div 3, Edu. Aim: A–C every round, D in one round out of three.','ABC every Saturday. Aim: A–E.','LeetCode Weekly (Sun 08:00 IST) when there was no round the night before.','One virtual Div 2 per week, upsolve D and E.'],
  'exit':['Rated 1600+ and held across 5 rated rounds','Div 2 A–C in under 60 minutes, 4 rounds in a row','Solve 7 of 10 random 1600-rated problems within 45 minutes','CSES Sorting & Searching, DP and Graph Algorithms fully done; Range Queries first 12','WA rate under 0.7 per accepted submission over the last 50']},
 {'name':'Expert to Candidate Master','band':'1600 → 1900','rank':'Expert → CM','lo':1600,'hi':1900,'months':'8–14 months',
  'goal':'Depth on trees and data structures. Solve Div 2 D reliably and E sometimes.',
  'topics':[T('USACO Guide: Gold, all modules',UG+'gold'),T('Segment tree with lazy propagation',CA+'data_structures/segment_tree.html#range-updates-lazy-propagation'),
   T('LCA, binary lifting',CA+'graph/lca_binary_lifting.html'),T('Euler tour + segment tree on trees',UG+'gold/tree-euler'),T('Rerooting DP',UG+'gold/all-roots'),
   T('Small-to-large merging, DSU on tree',CFB+'44351'),T('Bitmask DP',UG+'gold/dp-bitmasks'),T('SCC, bridges, articulation points',CA+'graph/strongly-connected-components.html'),
   T('MST, Bellman-Ford, Floyd-Warshall',CA+'graph/mst_kruskal_with_dsu.html'),T('KMP, Z-function',CA+'string/prefix-function.html'),T('Trie',UG+'gold/string-hashing'),
   T('Inclusion-exclusion',CA+'combinatorics/inclusion-exclusion.html'),T('Stars and bars, Catalan numbers',CA+'combinatorics/stars_and_bars.html'),
   T('Expected value and probability DP',UG+'gold/expected'),T('Game theory: Nim, Sprague-Grundy',CA+'game_theory/sprague-grundy-nim.html'),
   T('Meet in the middle',UG+'gold/meet-in-the-middle'),T('Sqrt decomposition, Mo\'s algorithm',CA+'data_structures/sqrt_decomposition.html'),
   T('Offline queries, sorting queries by right end',UG+'plat/offline-del'),T('Interactive problems'),T('Matrix exponentiation',CA+'algebra/binary-exp.html#applying-the-technique')],
  'cses':[4,5,3,6,7,9,13,15],
  'practice':[F('Mixed',[],1800,2100),F('Trees',['trees'],1700,2000),F('Data structures',['data structures'],1800,2100),F('DP',['dp'],1800,2100),F('Combinatorics',['combinatorics'],1700,2000),F('Strings',['strings'],1700,2000),F('Games',['games'],1600,1900)],
  'contests':['Every Div 2 and Edu. Once you are 1900+, every Div 1 instead; Div 1 + 2 combined rounds count either way. Aim: Div 2 A–D every round, E in one out of three; Div 1 A, B in one out of three.','ABC A–F on Saturday, ARC A–B on Sunday. LeetCode Weekly and Biweekly, aim all 4.','One virtual Div 2 or Edu per week. Upsolve E every time.'],
  'exit':['Rated 1900+ and held across 5 rated rounds','Div 2 A–D in under 90 minutes, 4 rounds in a row','Solve 7 of 10 random 1900-rated problems within 60 minutes','CSES Range Queries, Tree Algorithms and Graph Algorithms fully done; String Algorithms first 12','Mixed 1800–2100 filter: 100 solved']},
 {'name':'Candidate Master to Master','band':'1900 → 2100','rank':'CM → Master','lo':1900,'hi':2100,'months':'12–24 months',
  'goal':'Div 1 A and B every round. The hard theory arrives here, but most gains now come from ad-hoc speed.',
  'topics':[T('USACO Guide: Platinum, all modules',UG+'plat'),T('Convex hull trick, Li Chao tree',CA+'geometry/convex_hull_trick.html'),T('Divide-and-conquer DP',CA+'dynamic_programming/divide-and-conquer-dp.html'),
   T('Knuth optimization',CA+'dynamic_programming/knuth-optimization.html'),T('SOS DP',CFB+'45223'),T('Slope trick',CFB+'47821'),T('Broken profile DP',CA+'dynamic_programming/profile-dynamics.html'),
   T('HLD',CA+'graph/hld.html'),T('Centroid decomposition',UG+'plat/centroid'),T('Persistent segment tree',UG+'adv/persistent'),T('Treap',CA+'data_structures/treap.html'),
   T('Max flow, min cut, Dinic',CA+'graph/dinic.html'),T('Bipartite matching',CA+'graph/kuhn_maximum_bipartite_matching.html'),T('Min-cost flow',CA+'graph/min_cost_flow.html'),
   T('Suffix array',CA+'string/suffix-array.html'),T('Aho-Corasick',CA+'string/aho_corasick.html'),T('FFT / NTT',CA+'algebra/fft.html'),
   T('Möbius, multiplicative functions',CA+'algebra/phi-function.html'),T('Gaussian elimination, xor basis',CA+'linear_algebra/linear-system-gauss.html'),
   T('Basic geometry, convex hull',CA+'geometry/convex-hull.html'),T('Euler paths',CA+'graph/euler_path.html'),T('2-SAT',CA+'graph/2SAT.html')],
  'cses':[8,9,14,16],
  'practice':[F('Mixed',[],2100,2400),F('DP',['dp'],2100,2400),F('Flows',['flows'],2000,2300),F('Strings',['strings'],2000,2300),F('Math',['math'],2100,2400),F('Constructive',['constructive algorithms'],2000,2300),F('Data structures',['data structures'],2100,2400)],
  'contests':['Every Div 1. Aim: A–B every round, C in one out of three.','Div 2 only unrated now: use them as speed practice.','ARC A–C, AGC A. Two virtuals per week: one Div 1, one old Div 2 done as a speedrun.'],
  'exit':['Rated 2100+ and held across 5 rated rounds','Div 1 A–B in under 60 minutes, 4 rounds in a row','Solve 6 of 10 random 2200-rated problems within 90 minutes','CSES Advanced Techniques, Advanced Graph Problems and Mathematics done','Mixed 2100–2400 filter: 100 solved']},
 {'name':'Master to International Master','band':'2100 → 2300','rank':'Master → IM','lo':2100,'hi':2300,'months':'12–24 months',
  'goal':'Div 1 C reliably. Little new theory. Hard ad-hoc, deep constructive, and solve speed decide everything.',
  'topics':[T('USACO Guide: Advanced',UG+'adv'),T('Suffix automaton',CA+'string/suffix-automaton.html'),T('Polynomials: inverse, log, exp; Berlekamp-Massey',CFB+'61306'),
   T('Generating functions',CFB+'77468'),T('Burnside, Pólya',CA+'combinatorics/burnside.html'),T('Half-plane intersection',CA+'geometry/halfplane-intersection.html'),
   T('Splay tree, link-cut tree',UG+'adv/link-cut-tree'),T('Segment tree beats',CFB+'57319'),T('Dominator tree, hard flow modelling',UG+'adv/flow-lb'),
   T('Hard interactive and constructive: read Div 1 D editorials weekly'),T('Speed: every old Div 2 in under 90 minutes')],
  'cses':[16,17],
  'practice':[F('Mixed',[],2400,2700),F('Constructive',['constructive algorithms'],2300,2600),F('Interactive',['interactive'],2200,2500),F('Trees',['trees'],2300,2600),F('Math',['math'],2400,2700)],
  'contests':['Every Div 1 and every AGC. Aim: A–C every round.','Three virtuals per week, all Div 1, upsolve D every time.','Read every Div 1 editorial to E, even for rounds you skipped.'],
  'exit':['Rated 2300+. You are IM.','Div 1 A–C in under 90 minutes, 4 rounds in a row','Solve 6 of 10 random 2500-rated problems within 2 hours']},
]
RULES=[
 ('Timebox per problem','45 min at stage 0–1, 60 min at stage 2, 90 min at stage 3, 2 hours at stage 4. Then editorial, close it, code it yourself.'),
 ('Topic vs mixed practice','60/40 at stages 0–1. 40/60 at stage 2. 25/75 at stages 3–4. Rating comes from mixed practice; topics only remove excuses.'),
 ('Practice rating','Solve at your rating +200 to +400. If you solve 3 in a row easily, move up 100. If you fail 3 in a row, move down 100.'),
 ('Stages are gated by rating, not by date','Move to the next stage only when the exit checklist is done. Estimated months are a guess, not a deadline.'),
 ('Stalled for 3 months with the toolkit done?','The gap is speed or reading, not knowledge. Do only virtuals and upsolving for a month.'),
 ('Every month','Ask for the next month\'s daily plan. It comes from the current stage\'s topic list and your log.'),
]
